apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: weather-app
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.hosts.host | quote }}
      http:
        paths:
          {{- range .Values.ingress.hosts.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: weather-app
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}