name: Deploy to Kubernetes

on:
  repository_dispatch:
    types: [deploy]

env:
  AWS_REGION: us-east-1  # Change to your AWS region

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name your-cluster-name  # Change to your cluster name

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: '3.11.1'

      - name: Deploy to Kubernetes
        run: |
          helm upgrade --install weather-app ./helm-chart \
            --namespace ${{ github.event.client_payload.namespace }} \
            --create-namespace \
            --set image.tag=${{ github.event.client_payload.build_number }} \
            --set image.repository=rebachi/eks \
            --set service.type=ClusterIP \
            --set service.port=80 \
            --set service.targetPort=5000 \
            --set ingress.className=nginx \
            --wait
